musicapp/urls.py
from django.urls import path
from . import views
from . views import AlbumUpdateView, SongUpdateView

app_name = 'musicapp'

urlpatterns = [
	path('', views.index, name='index'),
	path('(?P<album_id>[0-9]+)/', views.detail, name='detail'),
	path('create_album/', views.create_album, name='create_album'),
	path('<int:pk>/update_album/', AlbumUpdateView.as_view(), name='album_update'),
	path('(?P<album_id>[0-9]+)/create_song', views.create_song, name='create_song'),
	path('(?P<album_id>[0-9]+)/delete_album', views.delete_album, name='delete_album'),
	path('(?P<album_id>[0-9]+)/delete_song/(?P<song_id>[0-9]+)/', views.delete_song, name='delete_song'),
	#path('<int:pk>/update_song/<int:pk>/', SongUpdateView.as_view(), name='update_song'),
	path('register/', views.register, name='register'),
	path('login/', views.login_user, name='login_user'),
	path('logout/', views.logout_user, name='logout_user'),
]

vcast/urls.py
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url('', include('musicapp.urls')),
   ]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

musicapp/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Album(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	name = models.CharField(max_length=25)
	artist = models.CharField(max_length=20)
	genre = models.CharField(max_length=15)
	cover = models.FileField()

	def __str__(self):
		return self.name


class Song(models.Model):
	album = models.ForeignKey(Album, on_delete=models.CASCADE)
	song_name = models.CharField(max_length=25)
	song_file = models.FileField()

	def __str__(self):
		return self.song_name

musicapp/forms.py
from django import forms
from . models import Album, Song, User


class AlbumForm(forms.ModelForm):

	class Meta:
		model = Album
		fields = ('name', 'artist', 'genre', 'cover')


class SongForm(forms.ModelForm):

	class Meta:
		model = Song
		fields = ('song_name', 'song_file')


class UserForm(forms.ModelForm):
	password = forms.CharField(widget=forms.PasswordInput)

	class Meta:
		model = User
		fields = ('username', 'email', 'password')

musicapp/views.py
from django.shortcuts import render, get_object_or_404, redirect, reverse
from . models import Album, Song
from . forms import AlbumForm, SongForm, UserForm
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from django.views.generic import UpdateView


# Create your views here
def index(request):
	albums = Album.objects.all()
	return render(request, 'musicapp/index.html', {'albums': albums})


def detail(request, album_id):
	album = get_object_or_404(Album, pk=album_id)
	return render(request, 'musicapp/detail.html', {'album': album})


class AlbumUpdateView(UpdateView):
	model = Album
	fields = ['name', 'artist', 'genre', 'cover']

	def form_valid(self, form):
		form.instance.author = self.request.user
		return super().form_valid(form)

	def test_func(self):
		album = self.get_object()
		if self.request.user == album.user:
			return True
		return False


@login_required(login_url='musicapp:login_user')
def create_album(request):
	form = AlbumForm(request.POST or None, request.FILES or None)
	if form.is_valid():
		album = form.save(commit=False)
		album.cover = request.FILES['cover']
		album.user = request.user
		album.save()
		return render(request, 'musicapp/detail.html', {'album': album})
	form = AlbumForm()
	return render(request, 'musicapp/create_album.html', {'form': form})


@login_required(login_url='musicapp:login_user')
def create_song(request, album_id):
	form = SongForm(request.POST or None, request.FILES or None)
	album = get_object_or_404(Album, pk=album_id)
	if form.is_valid():
		for s in album.song_set.all():
			if s.song_name == form.cleaned_data.get('song_name'):
				context = {'form': form,
						   'message': 'Already Added that song!'
						   }
				return render(request, 'musicapp/create_song.html', context)
		song = form.save(commit=False)
		song.album = album
		song.song_file = request.FILES['song_file']
		song.save()
		context = {'album': album,
				   'message': 'Song Added!'
				   }
		return render(request, 'musicapp/detail.html', context)
	form = SongForm()
	return render(request, 'musicapp/create_song.html', {'form': form})


def delete_album(request, album_id):
	album = Album.objects.get(pk=album_id)
	album.delete()
	albums = Album.objects.all()
	return render(request, 'musicapp/index.html', {'albums': albums})


class SongUpdateView(UpdateView):
	model = Song
	fields = ['song_name', 'song_file']

	def get_absolute_url(self):
		return reverse('musicapp:detail')

	def form_valid(self, form):
		return super().form_valid(form)


def delete_song(request, album_id, song_id):
	album = get_object_or_404(Album, pk=album_id)
	song = get_object_or_404(album.song_set, pk=song_id)
	song.delete()
	context = {'album': album,
			   'message': 'Song Deleted!'
			   }
	return render(request, 'musicapp/detail.html', context)


def register(request):
	form = UserForm(request.POST or None)
	if form.is_valid():
		user = form.save(commit=False)
		username = form.cleaned_data['username']
		password = form.cleaned_data['password']
		user.set_password(password)
		user.save()
		user = authenticate(username=username, password=password)
		if user is not None:
			if user.is_active:
				login(request, user)
				albums = Album.objects.filter(user=request.user)
				return render(request, 'musicapp/index.html', {'albums': albums})
	return render(request, 'musicapp/register.html', {'form': form})


def login_user(request):
	if request.method == 'POST':
		username = request.POST['username']
		password = request.POST['password']
		user = authenticate(username=username, password=password)
		if user is not None:
			if user.is_active:
				login(request, user)
				return redirect('musicapp:index')
	return render(request, 'musicapp/login.html')


def logout_user(request):
	logout(request)
	return redirect('musicapp:login_user')

musicapp/templates/musicapp/album_form.html
{% extends 'musicapp/base.html' %}

{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="text-primary">Update Album<small style="font-size: 24px;"> {{ object.name }}</small></h3>
                </div>
                <div class="panel-body">
                    <form method="post" action="" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'musicapp/form_template.html' %}

                        <div class="form-group">
                            <button type="submit" class="btn btn-success">Update</button>
                        </div>
                    </form>
                </div>

            </div>
        </div>
    </div>
</div>

{% endblock %}

musicapp/templates/musicapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    </head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'musicapp:index' %}">Boomba Track</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li> <a href="{% url 'musicapp:index' %}"><span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp; Home</a></li>

            </ul>
            <form class="navbar-form navbar-left" role="search" method="get" action="">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="{% url 'musicapp:create_album' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Album
                    </a>
                </li>
                {% if user.is_authenticated %}
                <li>
                    <a href="{% url 'musicapp:login_user' %}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                    </a>
                </li>
                {% else %}

                <li>
                    <a href="{% url 'musicapp:login_user' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Login
                    </a>
                </li>
                {% endif %}


            </ul>
        </div>

    </div>
</nav>

{% block content %}


{% endblock %}
</body>
</html>

musicapp/templates/musicapp/create_album.html
{% extends 'musicapp/base.html' %}

{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="text-primary">Add Album</h3>
                </div>
                <div class="panel-body">
                    <form method="post" action="" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'musicapp/form_template.html' %}

                        <div class="form-group">
                            <button type="submit" class="btn btn-success">Submit</button>
                        </div>
                    </form>
                </div>

            </div>
        </div>
    </div>
</div>

{% endblock %}

musicapp/templates/musicapp/create_song.html
{% extends 'musicapp/base.html' %}

{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="text-primary">Add Song</h3>
                </div>
                <div class="panel-body">
                    {% if message %}
                    <p class="text-danger"><b>{{ message }}</b></p>
                    {% endif %}
                    <form method="post" action="" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'musicapp/form_template.html' %}

                        <div class="form-group">
                            <button type="submit" class="btn btn-success">Submit</button>
                        </div>
                    </form>
                </div>

            </div>
        </div>
    </div>
</div>
{% endblock %}

musicapp/templates/musicapp/detail.html
{% extends 'musicapp/base.html' %}

{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-3">
            <div class="thumbnail">
                <img src="{{ album.cover.url }}" class="img img-responsive" style="height: 250px; width: 200px;">

                <div class="caption">
                    <h4>{{ album.name }}</h4>
                    <h5>{{ album.artist }}</h5>
                </div>
            </div>
        </div>

        <div class="col-sm-9">
            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation" class="active"><a href="">Songs</a></li>
                <li role="presentation"><a href="{% url 'musicapp:create_song' album.id %}">Add song</a> </li>
            </ul>

            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="text-center text-primary">Songs</h3>
                </div>

                <div class="panel-body">
                {% if message %}
                    <p class="text-success"><strong>{{ message }}</strong></p>
                {% endif %}
                    <table class="table">
                        <thead>
                        <tr>
                         <th>Name</th>
                         <th>Audio</th>
                         <th>Favorite</th>
                         <th>Action</th>
                        </tr>
                        </thead>

                        {% if album.song_set %}
                            {% for song in album.song_set.all %}
                            <tr>
                            <td>{{ song.song_name }}</td>

                            <td>
                                <a target="_blank" href="{{ song.song_file.url }}">
                                   <button type="button" class="btn btn-success btn-xs">
                                       <span class="glyphicon glyphicon-play"></span>&nbsp;Play
                                   </button>
                                </a>
                            </td>

                            <td>
                                <a href="">
                                <span class="glyphicon glyphicon-star"></span>
                                </a>
                            </td>

                            <td>
                                <a href="{% url 'musicapp:delete_song' album.id song.id %}">
                                    <button type="button" class="btn btn-danger btn-xs">
                                        <span class="glyphicon glyphicon-trash"></span>&nbsp;Delete
                                    </button>
                                </a>&nbsp;
                                <a href="{% url 'musicapp:update_song' album.id song.id %}">
                                    <button type="button" class="btn btn-info btn-xs">
                                        <span class="glyphicon glyphicon-pencil"></span>&nbsp;Update
                                    </button>
                                </a>
                            </td>
                            </tr>

                            {% endfor %}

                        {% endif %}
                    </table>
                </div>

            </div>
        </div>





    </div>
</div>
{% endblock %}

musicapp/templates/musicapp/form_template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2" for="song_title">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

musicapp/templates/musicapp/index.html
{% extends 'musicapp/base.html' %}

{% block content %}
<div class="container-fluid">
    <div class="row">
        <h3 class="text-center text-primary">
            {{ request.user.username }} <b>Albums</b>
            <hr>
        </h3>
        {% if albums %}
            {% for album in albums %}
        <div class="col-sm-3">
            <div class="thumbnail">
                <a href="{% url 'musicapp:detail' album.id %}">
                <img src="{{ album.cover.url }}" class="img img-responsive" style="height: 250px; width: 200px;" alt="">
                </a>
                    <div class="caption">
                    <h4>{{ album.name }}</h4>
                    <h5>{{ album.artist }}</h5>
                        <form method="post" action="{% url 'musicapp:delete_album' album.id %}">
                            {% csrf_token %}
                            <input type="hidden" name="album_id" value="{{ album.id }}">
                            <a href="{% url 'musicapp:delete_album' album.id %}">
                            <span class="glyphicon glyphicon-trash"></span>
                            </a>&nbsp;&nbsp;
                            <a href="">
                                <span class="glyphicon glyphicon-pencil"></span>
                            </a>
                        </form>
                </div>
            </div>
        </div>
            {% endfor %}
        {% endif %}
    </div>
</div>
{% endblock %}

musicapp/templates/musicapp/login.html
{% extends 'musicapp/base.html' %}

{% block content %}
    <div class="container-fluid">
    <div class="row">
        <div class="col-md-4">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3>Login</h3>
                </div>

                <div class="panel-body">
                    <form class="form-horizontal" action="" method="post" style="margin: 15px;">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="control-label">Username:</label>
                            <input type="text" class="form-control" name="username" >
                        </div>

                        <div class="form-group">
                            <label class="control-label">Password:</label>
                            <input type="password" class="form-control" name="password" >
                        </div>

                        <div class="form-group">
                            <button type="submit" class="btn btn-success">Login</button>
                        </div>
                        <div>
                            <p> Not Registered? <a href="{% url 'musicapp:register' %}">Register</a></p>
                        </div>
                    </form>
                </div>

            </div>
        </div>
    </div>
    </div>
{% endblock %}

musicapp/templates/musicapp/register.html
{% extends 'musicapp/base.html' %}

{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="text-primary">Sign Up</h3>
                </div>
                <div class="panel-body">
                    <form method="post" action="" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'musicapp/form_template.html' %}

                        <div class="form-group">
                            <button type="submit" class="btn btn-success">Submit</button>
                        </div>
                        <div>
                            <p>Already Registered? <a href="{% url 'musicapp:login_user' %}">Login</a> </p>
                        </div>
                    </form>
                </div>

            </div>
        </div>
    </div>
</div>

{% endblock %}